version: "3.7"
services:
  nginx-server:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - bootcampnet
    depends_on:
      - backend
  backend:
    image: ${BACK_IMAGE_TAG}
    container_name: "go-backend"
    ports:
      - 8080:8080
    networks:
      - bootcampnet
  frontend:
    image: ${FRONT_IMAGE_TAG}
    container_name: "js-frontend"
    ports:
      - 3000:3000
    networks:
      - bootcampnet
networks:
  bootcampnet: