version: "3.9"
services:
  nginx-server:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - fintechnet
    depends_on:
      - backend
  backend:
    image: ${BACK_IMAGE_TAG}
    container_name: "go-backend"
    ports:
      - 8080:8080
    networks:
      - fintechnet
  frontend:
    image: ${FRONT_IMAGE_TAG}
    container_name: "js-frontend"
    environment:
      - REACT_APP_BACKEND_API=localhost
    ports:
      - 3000:3000
    networks:
      - fintechnet
networks:
  fintechnet:
